[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "como_recipes"
version="0.1.0"
authors = [
  { name="Cody Baker", email="cody.c.baker.phd@gmail.com" },
]
description = "Collection of recipes and meal planning software for our household."
readme = "README.md"
requires-python = ">=3.13,<3.14"
license = {file = "license.txt"}

keywords = ["recipes", "cooking"]

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
]

dependencies = [
    "pydantic",
    "click",
    "natsort",
]

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.toml
  |\.yml
  |\.txt
  |\.sh
  |\.git
  |\.ini
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[project.urls]
"Homepage" = "https://github.com/CodyCBakerPhD/como_recipes"
"Bug Tracker" = "https://github.com/CodyCBakerPhD/como_recipes/issues"

[project.scripts]
write_missing_markdown_recipes = "como_recipes._command_line_interface:_write_missing_markdown_recipes"
write_missing_pydantic_recipes = "como_recipes._command_line_interface:_write_missing_pydantic_recipes"
como_recipes = "como_recipes._command_line_interface:_como_recipes_command_line_interface_main_entrypoint"



[tool.ruff]
exclude = [
    "*/__init__.py"
]
line-length = 120

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "D",
    # Skipping UP due to a lot of unsafe or opinionated/not rigorously proven rules
    "YTT",
    "ANN",
    "ASYNC",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    # Skip CPY
    "C4",
    "DTZ",
    "T10",
    "DJ",
    "EM",
    "EXE",
    "FA",
    "ISC",
    "ICN",
    "LOG",
    "G",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "SIM",
    "TID",
    "TCH",
    "INT",
    "ARG",
    "PTH",
    "TD",
]
ignore = [
    "D401",  # Ignore the imperative mood convention for docstrings
    "D203",  # Ignore no blank lines after class docstring in favor of D203 (one blank line) as convention
    "D212",  # Ignore multi-line summary on first line in favor of D213 (second line) as convention
    "D402",  # False positives with this one
    "ANN101",  # Deprecated and will be removed soon
    "ANN102",  # Deprecated and will be removed soon
    "DTZ005",  # Timezone can't easily be detected to use for timestamping; we also just don't need it for anything
    "ICN001",  # Controversial opinion: I prefer fully explicit naming to avoid any potential confusion
    "PYI041",  # Disagree with
    "TID252",  # The PEP says that explicit relative imports are an acceptable alternative, but check doesn't care...
    "TD",  # I like in general, but will add back in later
]

[tool.ruff.lint.per-file-ignores]
"src/como_recipes/__init__.py" = ["I"]  # Must maintain explicit order for imports for registration
"src/como_recipes/_recipes/_pydantic/*" = ["E501"]  # Automated Pydantic conversion occasionally exceeds line length
"src/como_recipes/_command_line_interface.py" = [
    "S605",  # Console injections are manually OK'd
    "BLE001",  # logging is manually OK'd
    "T20",  # print statements are fine in command line interfaces
]
"tests/*" = [  # Neither docstrings nor annotations are required for tests
    "D100",
    "D103",
    "ANN201",
    "S101",  # Assert statements are the best way to get diffs with pytest
    "INP001",  # Not really a part of the package
    "T20",  # print statements are fine in tests since they can help render debugging info in GitHub Actions logs
]

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
known-first-party = ["como_recipes"]



[tool.codespell]
skip = '.git*,*.pdf,*.css'
check-hidden = true
