[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "como_recipes"
version="0.1.0"
authors = [
  { name="Cody Baker", email="cody.c.baker.phd@gmail.com" },
]
description = "Collection of recipes and meal planning software for our household."
readme = "README.md"
requires-python = ">=3.13,<3.14"
license = {file = "license.txt"}

keywords = ["recipes", "cooking"]

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
]

dependencies = [
    "pydantic",
    "click",
    "natsort",
]

[tool.black]
line-length = 120
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.toml
  |\.yml
  |\.txt
  |\.sh
  |\.git
  |\.ini
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[project.urls]
"Homepage" = "https://github.com/CodyCBakerPhD/como_recipes"
"Bug Tracker" = "https://github.com/CodyCBakerPhD/como_recipes/issues"

[project.scripts]
write_missing_markdown_recipes = "como_recipes._command_line_interface:_write_missing_markdown_recipes"
write_missing_pydantic_recipes = "como_recipes._command_line_interface:_write_missing_pydantic_recipes"
como_recipes = "como_recipes._command_line_interface:_como_recipes_command_line_interface_main_entrypoint"



[tool.ruff]
exclude = [
  "*/__init__.py"
]
line-length = 120

[tool.ruff.lint]
select = ["F", "E", "W"]

[tool.ruff.lint.per-file-ignores]
"src/como_recipes/__init__.py" = ["I"]  # Must maintain explicit order for imports for registration
"src/como_recipes/_recipes/_pydantic/*" = ["E501"]  # Automated Pydantic conversion occasionally exceeds line length

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
known-first-party = ["como_recipes"]



[tool.codespell]
skip = '.git*,*.pdf,*.css'
check-hidden = true
