name: Bug Report
description: Report a bug from the interactive command line tool.
title: "[Bug]: "
labels: ["category: bug"]

body:
  - type: markdown
    attributes:
      value: |
        # Thank you for taking the time to fill out this bug report!
        ### The following information will help us resolve your issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        What were you trying to do?

        Please describe the 
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Traceback or log file
      description: When using the interactive command line tool, a log file should have automatically opened when the error occured.
      value: "Copy & paste or directly upload the log file of the error traceback here"
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS - Silicon
        - macOS - Intel
        - Linux
        - N/A
      default:
        - N/A
  - type: dropdown
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CodyCBakerPhD/como_recipes/blob/main/.github/CODE_OF_CONDUCT.rst)
      options:
        - "Yes"
