# These imports must be listed here explicitly to trigger imports and registration automatically
from ._yellow_cake import YellowCake
from ._whipped_cream_cheese_filling import WhippedCreamCheeseFilling
from ._whipped_chocolate_icing import WhippedChocolateIcing
from ._vegetarian_gravy import VegetarianGravy
from ._tamari_sauce import TamariSauce
from ._taco_seasoning import TacoSeasoning
from ._sweet_fire_rub import SweetFireRub
from ._sweet_dough import SweetDough
from ._strawberry_jam import StrawberryJam
from ._stir_fry import StirFry
from ._spanish_rice import SpanishRice
from ._spaghetti_squash import SpaghettiSquash
from ._sourdough import Sourdough
from ._slow_cooked_ribs import SlowCookedRibs
from ._sloppy_joe import SloppyJoe
from ._simple_caramel import SimpleCaramel
from ._shortening_pie_crust import ShorteningPieCrust
from ._shortbread import Shortbread
from ._sauteed_mushrooms import SauteedMushrooms
from ._roast_turkey import RoastTurkey
from ._roast_pumpkin import RoastPumpkin
from ._sauteed_green_beans import SauteedGreenBeans
from ._cream_fudge import CreamFudge
from ._rice import Rice
from ._gingerbread_cookies import GingerbreadCookies
from ._red_wine_sauce import RedWineSauce
from ._red_beans import RedBeans
from ._ratatouille import Ratatouille
from ._pumpkin_pie_filling import PumpkinPieFilling
from ._pumpkin_cream_coffee_sauce import PumpkinCreamCoffeeSauce
from ._pot_pie import PotPie
from ._potatoes_au_gratin import PotatoesAuGratin
from ._pizza_crust import PizzaCrust
from ._pancakes import Pancakes
from ._nutella_bites import NutellaBites
from ._mochi_donuts import MochiDonuts
from ._mirror_glaze import MirrorGlaze
from ._millionaire_shortbread import MillionaireShortbread
from ._macaroni_and_cheese import MacaroniAndCheese
from ._key_lime_filling import KeyLimeFilling
from ._kale_soup import KaleSoup
from ._kaiser_roll import KaiserRoll
from ._jerk_rub import JerkRub
from ._italian_meringue import ItalianMeringue
from ._honey_garlic_salmon import HoneyGarlicSalmon
from ._happy_plums import HappyPlums
from ._green_chili import GreenChili
from ._green_bean_casserole import GreenBeanCasserole
from ._grape_salad import GrapeSalad
from ._frying_breading import FryingBreading
from ._fried_rice import FriedRice
from ._fried_not_chicken import FriedNotChicken
from ._fried_chicken import FriedChicken
from ._fettuccine_alfredo import FettuccineAlfredo
from ._falafel import Falafel
from ._enchilada_sauce import EnchiladaSauce
from ._enchilada_beef import EnchiladaBeef
from ._doughnuts import Doughnuts
from ._creamed_genoise import CreamedGenoise
from ._cornbread_dressing import CornbreadDressing
from ._cornbread import Cornbread
from ._collard_greens import CollardGreens
from ._cobbler_topping import CobblerTopping
from ._chocolate_ganache import ChocolateGanache
from ._chocolate_fudge import ChocolateFudge
from ._chocolate_doughnut_icing import ChocolateDoughnutIcing
from ._chocolate_dome_cake import ChocolateDomeCake
from ._chocolate_chip_cookies import ChocolateChipCookies
from ._chocolate_cake import ChocolateCake
from ._cherry_pie_filling import CherryPieFilling
from ._carnitas import Carnitas
from ._cabbage_rolls import CabbageRolls
from ._butter_pie_crust import ButterPieCrust
from ._buttermilk_waffles import ButtermilkWaffles
from ._buffalo_wings import BuffaloWings
from ._brownie_icing import BrownieIcing
from ._brownies import Brownies
from ._broccoli_cheddar_soup import BroccoliCheddarSoup
from ._brigadeiros import Brigadeiros
from ._black_bean_chili import BlackBeanChili
from ._beer_batter import BeerBatter
from ._bechamel_sauce import BechamelSauce
from ._banana_bread import BananaBread
from ._baked_potato import BakedPotato
from ._apple_pie_filling import ApplePieFilling
from ._applesauce import Applesauce
from ._aglio_e_olio import AglioEOlio
