name: Deploy Executable
description: Deploy a single executable for a platform/architecture/version combination.
inputs:
  os:
    description: Operating system (versioned)
    required: true

runs:
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Fresh install of package
      run: python -m pip install -e .

    - name: Get package version
      id: package_version
      run: python -c "import importlib.metadata; import os; v='value=v'+importlib.metadata.version(distribution_name='como_recipes'); io = open(file=os.environ['GITHUB_OUTPUT'], mode='a'); print(v, file=io); io.close()"

    - name: Fresh install of package
      run: python -m pip install -e .

    - name: Install PyInstaller
      run: python -m pip install pyinstaller

    - name: Build Executable with PyInstaller
      run: pyinstaller --onefile src/como_recipes/_interactive_console_builder.py --name como_recipes-${{ inputs.os }}-${{ steps.package_version.outputs.value }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/como_recipes-${{ inputs.os }}-${{ steps.package_version.outputs.value }}.exe
        asset_name: como_recipes-${{ inputs.os }}-${{ steps.package_version.outputs.value }}.exe
        tag: ${{ steps.package_version.outputs.value }}
        overwrite: true
          body: "${{ env.package_version }} release of the CoMo Recipes interactive console."
          draft: true
