name: Deploy Executable
description: Deploy a single executable for a platform/architecture/version combination.
inputs:
  os:
    description: Operating system (versioned)
    required: true
  GITHUB_TOKEN:
    description: The secret GitHub token with admin privileges
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Fresh install of package
      run: python -m pip install -e .
      shell: bash

    - name: Get package version
      id: package_version
      run: python -c "import importlib.metadata; import os; v='value=v'+importlib.metadata.version(distribution_name='como_recipes'); io = open(file=os.environ['GITHUB_OUTPUT'], mode='a'); print(v, file=io); io.close()"
      shell: bash

    - name: Fresh install of package
      run: python -m pip install -e .
      shell: bash

    - name: Install PyInstaller
      run: python -m pip install pyinstaller
      shell: bash

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller \
          --onefile src/como_recipes/_interactive_console_builder.py \
          --name como_recipes-${{ inputs.os }}-${{ steps.package_version.outputs.value }} \
          --icon src/como_recipes/_assets/como_icon.ico \
          --add-data src/como_recipes/_assets/como_icon.ico
      shell: bash

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.GITHUB_TOKEN }}
        file: ./dist/como_recipes-${{ inputs.os }}-${{ steps.package_version.outputs.value }}.exe
        asset_name: como_recipes-${{ inputs.os }}-${{ steps.package_version.outputs.value }}.exe
        tag: ${{ steps.package_version.outputs.value }}
        release_name: ${{ steps.package_version.outputs.value }}
        body: ${{ steps.package_version.outputs.value }} release of the CoMo Recipes interactive console.
        overwrite: true  # Per-asset not per-release
        draft: true
