name: Run tests and upload coverage report
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: 'CodeCov Token for uploading coverage reports'
        required: true

jobs:

  run:
    # Will read on PR dashboard as 'Review / coverage / ubuntu'
    # Action dashboard identified by 'Run tests and upload coverage report'
    # Requirement settings identified as 'coverage / ubuntu'
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Get date
        id: get_date
        run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore cached virtualenv
        uses: actions/cache/restore@v6
        with:
          key: ${{ steps.get_date.outputs.date }}-${{ hashFiles('pyproject.toml') }}
          path: ~/coverage_environment

      - name: Install Pytest
        run: |
          python -m venv ~/coverage_environment
          source ~/coverage_environment/bin/activate
          python -m pip install -U pip
          python -m pip install pytest-cov
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Save cached virtualenv
        uses: actions/cache/save@v6
        with:
          key: ${{ steps.get_date.outputs.date }}-${{ hashFiles('pyproject.toml') }}
          path: ~/coverage_environment

      - name: Fresh install of package
        run: python -m pip install -e .

      - name: Run pytest with coverage and printout coverage for debugging
        run: |
          pytest tests -vv -rsx --cov=como_recipes --cov-report xml:./coverage.xml
          cat ./coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CodyCBakerPhD/como_recipes
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
