name: Deploy Executables
run-name: ${{ github.actor }} is deploying a release for CoMo Recipes

on:
  workflow_dispatch:

jobs:
  build_and_deploy_windows_2022:
    name: Build and deploy with Windows 2022
    runs-on: windows-2022

    steps:
      - name: Checkout repo so local actions can be used
        uses: actions/checkout@v4

      - name: Deploy executable
        uses: ./.github/actions/deploy_executable
        with:
          os: windows-2022
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy_windows_2019:
    name: Build and deploy with Windows 2019
    needs: [build_and_deploy_windows_2022]
    runs-on: windows-2019

    steps:
      - name: Checkout repo so local actions can be used
        uses: actions/checkout@v4

      - name: Deploy executable
        uses: ./.github/actions/deploy_executable
        with:
          os: windows-2019
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
