name: Deploy

on:
  push:  # Would prefer `pull_request`, but custom pre-commit has trouble with refs; for private repo not a huge diff

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pre-commit:
    uses: ./.github/workflows/pre_commit.yml
    secrets:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

  tests:
    needs: pre-commit
    uses: ./.github/workflows/testing.yml
