name: Deploy Executable
run-name: ${{ github.actor }} is deploying a release for ${{ github.event.inputs.os }}

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Operating system, including version
        options:
        - windows-2022
        - windows-2019

jobs:
  build_and_deploy:
    name: Build and deploy interactive console
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Checkout repo so local actions can be used
        uses: actions/checkout@v4

      - name: Deploy executable
        uses: ./.github/actions/deploy_executable
        with:
          os: ${{ github.event.inputs.os }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
