name: Review

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Coverage:
    if: github.event.review.state == 'approved'
    uses: ./.github/workflows/coverage.yml
    secrets:
      CODECOV_CREDENTIALS: ${{ secrets.CODECOV_CREDENTIALS }}
