name: Deploy

on:
  push:  # Would prefer on `pull_request`, but custom pre-commit bot has trouble with refs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pre-commit:
    uses: ./.github/workflows/pre_commit.yml
    secrets:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

  tests:
    needs: pre-commit
    uses: ./.github/workflows/testing.yml
