name: Installation
on: pull_request
jobs:
  run:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: s-weigand/setup-conda@v1
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pytest
        run: |
          pip install --upgrade pip
          pip install .
