name: pre-commit
on:
  workflow_call:
    secrets:
      API_TOKEN_GITHUB:
        description: 'GitHub Token for pushing back automatic changes'
        required: true

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / pre-commit / run'
    # Action dashboard identified by 'pre-commit'
    # Requirement settings identified as 'pre-commit / run'
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        ref: ${{ github.head_ref }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository

    - name: Set cache hash
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Cache pre-commit
      id: cache-pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - if: steps.cache-pre-commit.outputs.cache-hit == false
      name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files

    - name: Determine if changes were made
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
            echo "CHANGES=true" >> $GITHUB_ENV;
        fi

    - name: Commit files
      run: | # `|| true` below to skip if nothing changed from pre-commit
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "pre-commit" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: ${{ github.ref }}
#        force: true

    - name: Send fail signal if changes were detected
      if: env.CHANGES == 'true'
      run: exit 1
