name: pre-commit
on:
  workflow_call:
    secrets:
      API_TOKEN_GITHUB:
        description: 'GitHub Token for pushing back automatic changes'
        required: true

jobs:

  run:
    # Will read on PR dashboard as 'Deploy / pre-commit / run'
    # Action dashboard identified by 'pre-commit'
    # Requirement settings identified as 'pre-commit / run'
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}  # Requires a custom token to re-trigger from pre-commit
        ref: ${{ github.head_ref }}
        persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN
        fetch-depth: 0  # otherwise, there would be errors pushing refs to the destination repository
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Set cache hash
      run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
    - name: Cache pre-commit
      id: cache-pre-commit
      uses: actions/cache@v4
      with:
        path: |
          ~/pre_commit_environment
          ~/.cache/pre-commit/
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}|${{ hashFiles('pyproject.toml') }}
    - if: steps.cache-pre-commit.outputs.cache-hit == false
      name: Install a virtual environment with pre-commit
      run: |
        python -m venv ~/pre_commit_environment
        source ~/pre_commit_environment/bin/activate
        python -m pip install -U pip
        python -m pip install pre-commit
        pre-commit install
        pip install -e .  # Install the package to be able to run the local hook

    - name: Run pre-commit
      run: | # Run thrice for error when pre-commit is missing; also because situations have been seen requiring three runs
        source ~/pre_commit_environment/bin/activate
        pre-commit run --all-files || pre-commit run --all-files || pre-commit run --all-files

    - name: Determine if changes were made
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
            echo "CHANGES=true" >> $GITHUB_ENV;
        fi

    - name: Commit files
      run: |  # `|| true` below to skip if nothing changed from pre-commit
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "pre-commit" -a || true

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: ${{ github.ref }}

    - name: Send fail signal if changes were detected
      if: env.CHANGES == 'true'
      run: exit 1
