name: Installation
on: pull_request
jobs:
  run:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
#        with:
#          requirement_files: requirements.txt  # this is optional
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit == false

      - name: Install pytest
        if: steps.cache-virtualenv.outputs.cache-hit == false
        run: |
          pip install --upgrade pip
          pip install .
          pip install pytest
      - name: Run Tests
        run: pytest
