name: Installation
on: pull_request
jobs:
  run:
    name: Install and run tests if non-markdown file changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
  
#    name: Install
#    runs-on: ubuntu-latest
#    steps:
#      - uses: s-weigand/setup-conda@v1
#      - uses: actions/checkout@v2
#      - run: git fetch --prune --unshallow --tags
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#      - name: Install pytest
#        run: |
#          pip install --upgrade pip
#          pip install .
